### ISSUE TITLE
[Bug] Upload PDF not working

### ISSUE THREAD

**Issue by Roaster05** [AOSSIE-Org/EduAid#14] opened 2024-03-12 14:26 UTC
### Expected Output:
While uploading the `application/pdf` type of file its text content should have been rendered in the inputbox's content
### How to Reproduce:
- Open the extension Popup and click on **Upload PDF** button
-  Select an `application/pdf` type of file from your local system 
-  No changes will be detected even after uploading the file

### Reasons:
The popup is being displayed using the `text_input.html` file where the file is being uploaded using the `input` tag, this html file is using the script `text_input.js` where the implementation of accessing the pdf's text content is done using an external library `pdfjsLib` which isn't imported any where in the extension's repository and hence it is not able to access the text content of the pdf being uploaded, also the **Content-Security-Policy** doesn't allow external scripts to be imported .

[Screencast.webm](https://github.com/AOSSIE-Org/EduAid/assets/100672872/2af97244-5c40-467b-8ba6-6a7b9183d6e0)

**Comment by IcyArse** [comment] 2024-03-12 21:28
Would changing the input variable to directly go into forms text_input.html and try to remove the need of external library be a helpful solution? I would like to try out this issue as someone trying to enter open source development.

**Comment by Roaster05** [comment] 2024-03-13 07:28
> Would changing the input variable to directly go into forms text_input.html and try to remove the need of external library be a helpful solution? I would like to try out this issue as someone trying to enter open source development.

I have fixed that already in my recent PR #15, Thanks anyway

**Comment by Raghucharan16** [comment] 2024-03-16 04:55
If the issue is closed, close the issue.🤓
If it is still open, I can work on it.
thanks.

**Comment by Roaster05** [comment] 2024-03-16 08:48
> If the issue is closed, close the issue.🤓 If it is still open, I can work on it. thanks.

Hello @Raghucharan16 the issue has still not recieved any comments from the **assigned mentors**  so this will be kept open till then , although a PR has already been made associated with this issue.

**Comment by Raghucharan16** [comment] 2024-03-16 09:11
Yeah @Roaster05 saw that. Thought I would give a try to that.

**Comment by Gorachand-Senapati** [comment] 2024-11-30 15:05
@Roaster05 this issue till open , can I work on this?

**Comment by sanks011** [comment] 2024-12-15 06:01
@Roaster05 is this issue still open? can I contribute?

**Closed** 2024-12-17 04:45 UTC
